### ISSUE TITLE
I don't understand 'm' flag! error when "make vpmac"

### ISSUE THREAD

**Issue by Jan91** [jbwhit/til#3]
Hi Jonathan:

I was following your instructions on how to install VPfit on Mac, which works perfectly
fine until I get the following error. Any ideas how to solve this problem?
(I am using OS X version: Sierra 10.12.3)

:make vpmac
/usr/local/Cellar/gcc/6.3.0_1/bin/gfortran -O -Wall   -c -o vpgti.o vpgti.f
FATAL:/opt/local/bin/../libexec/as/x86_64/as: I don't understand 'm' flag!
make: *** [vpgti.o] Error 1

Attached is my Makefile (as .txt)

[Makefile.txt](https://github.com/jbwhit/til/files/730572/Makefile.txt)

Thanks you very much and cheers,

Jan

**Comment by Jan91** [comment]
Solved by using the g77 compiler!

**Comment by jbwhit** [comment]
Glad you got this worked out!

**Comment by harrycosmos** [comment]
Hi Jonathan
I am also trying to install vpfit on my mac os sierra,  by simply using the "make vpmac" command after installing the cfitsio and pgplot via macport. I exactly get the same error as Jan received.
By using g77 instead of gfortran, I get the follwoing error:
g77 -O -Wall  -c -o vp_errej.o vp_errej.f
g77 -O -Wall  -c -o vp_ewred.o vp_ewred.f
vp_ewred.f: In subroutine `vp_ewred':
vp_ewred.f:97: 
             open(unit=18,file=atomdr,status='OLD',
             ^
Unsupported OPEN control item at (^) -- ACTION=, ASSOCIATEVARIABLE=, BLOCKSIZE=, BUFFERCOUNT=, CARRIAGECONTROL=, DEFAULTFILE=, DELIM=, DISPOSE=, EXTENDSIZE=, INITIALSIZE=, KEY=, MAXREC=, NOSPANBLOCKS, ORGANIZATION=, PAD=, POSITION=, READONLY=, RECORDTYPE=, SHARED=, and USEROPEN= are not supported
vp_ewred.f:105: 
           open(unit=18,file=atomdr,status='OLD',position='REWIND',
           ^
Unsupported OPEN control item at (^) -- ACTION=, ASSOCIATEVARIABLE=, BLOCKSIZE=, BUFFERCOUNT=, CARRIAGECONTROL=, DEFAULTFILE=, DELIM=, DISPOSE=, EXTENDSIZE=, INITIALSIZE=, KEY=, MAXREC=, NOSPANBLOCKS, ORGANIZATION=, PAD=, POSITION=, READONLY=, RECORDTYPE=, SHARED=, and USEROPEN= are not supported
vp_ewred.f:108: 
         open(unit=18,file=atomdr,status='OLD',position='REWIND',
         ^
Unsupported OPEN control item at (^) -- ACTION=, ASSOCIATEVARIABLE=, BLOCKSIZE=, BUFFERCOUNT=, CARRIAGECONTROL=, DEFAULTFILE=, DELIM=, DISPOSE=, EXTENDSIZE=, INITIALSIZE=, KEY=, MAXREC=, NOSPANBLOCKS, ORGANIZATION=, PAD=, POSITION=, READONLY=, RECORDTYPE=, SHARED=, and USEROPEN= are not supported
vp_ewred.f:117: 
         open(unit=18,file=atomdr,status='OLD',position='REWIND',
         ^
Unsupported OPEN control item at (^) -- ACTION=, ASSOCIATEVARIABLE=, BLOCKSIZE=, BUFFERCOUNT=, CARRIAGECONTROL=, DEFAULTFILE=, DELIM=, DISPOSE=, EXTENDSIZE=, INITIALSIZE=, KEY=, MAXREC=, NOSPANBLOCKS, ORGANIZATION=, PAD=, POSITION=, READONLY=, RECORDTYPE=, SHARED=, and USEROPEN= are not supported
vp_ewred.f:149: 
         open(unit=18,file=filnm,status='OLD',position='REWIND',err=99)
         ^
Unsupported OPEN control item at (^) -- ACTION=, ASSOCIATEVARIABLE=, BLOCKSIZE=, BUFFERCOUNT=, CARRIAGECONTROL=, DEFAULTFILE=, DELIM=, DISPOSE=, EXTENDSIZE=, INITIALSIZE=, KEY=, MAXREC=, NOSPANBLOCKS, ORGANIZATION=, PAD=, POSITION=, READONLY=, RECORDTYPE=, SHARED=, and USEROPEN= are not supported
make: *** [vp_ewred.o] Error 1

Any idea?

Thanks 
Harry

**Comment by jbwhit** [comment]
First guess is that macports and homebrew are installing cfitsio/pgplot into different paths.

**Comment by harrycosmos** [comment]
Hi Jonathan
IT was like a conflict between macports and brew. I redid everything and it works now. I need to do some practice with vpfit and rdgen. Is there any RD PRSETUP RDSTART  and VPFSETUP sample file and any tutorial material to start with.

**Comment by jbwhit** [comment]
Glad to hear that it works now -- the best documentation that I've found
for these are the pdf manuals themselves here:
https://www.ast.cam.ac.uk/~rfc/vpfit.html

--
Jonathan Whitmore, PhD
Web: JonathanWhitmore.com <http://jonathanwhitmore.com/>
US (Google Voice): +1 (321) 252 9448
